GET  https://127.0.0.1:56901/api/cluster-info
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjAxUnNSSzRhNjJWOXZYdGVZYk81TkhLLXYtUVlKVzg1QUJCVkVnRW9hRjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImM5ODZjNWFlLWZkNjgtNDE1ZS1iODlmLTA4NThlOTIwZWFmZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.o_w_2dA86_ZOKZTfuiaeb5FKIb_GxUsY0IcpZJd5wUcNTTP5b01w4NxNqPUF6SRunbpPWM3sQPwyOyBQ1hqabBW1OKxFnWenmPMJEuy3DVT1ohS4Y833OdiJnHTmiIP97J_VfzYDejBYY09oyih-KDUZcUyfBaIF2tZUSl2I79HsPa2wwVwuW-HX0A4D3lUki_c-QYtaPp5_n-xUh1mrQSJDVVHigh0f5od6eWPZ2enXRNZOONV1HZEQpdDHcF5cdT4CPsapfY4gOKsEGZH1F-kLhQDgGKiHprRDAna0E4LC6orMsUFMuEJIYqweyXvYbO_apSG-X7IiomOt-mYA1w

###
GET  https://127.0.0.1:56901/api/namespace/default/pods
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjAxUnNSSzRhNjJWOXZYdGVZYk81TkhLLXYtUVlKVzg1QUJCVkVnRW9hRjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImM5ODZjNWFlLWZkNjgtNDE1ZS1iODlmLTA4NThlOTIwZWFmZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.o_w_2dA86_ZOKZTfuiaeb5FKIb_GxUsY0IcpZJd5wUcNTTP5b01w4NxNqPUF6SRunbpPWM3sQPwyOyBQ1hqabBW1OKxFnWenmPMJEuy3DVT1ohS4Y833OdiJnHTmiIP97J_VfzYDejBYY09oyih-KDUZcUyfBaIF2tZUSl2I79HsPa2wwVwuW-HX0A4D3lUki_c-QYtaPp5_n-xUh1mrQSJDVVHigh0f5od6eWPZ2enXRNZOONV1HZEQpdDHcF5cdT4CPsapfY4gOKsEGZH1F-kLhQDgGKiHprRDAna0E4LC6orMsUFMuEJIYqweyXvYbO_apSG-X7IiomOt-mYA1w

###
GET  https://127.0.0.1:56901/api/
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjAxUnNSSzRhNjJWOXZYdGVZYk81TkhLLXYtUVlKVzg1QUJCVkVnRW9hRjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImM5ODZjNWFlLWZkNjgtNDE1ZS1iODlmLTA4NThlOTIwZWFmZiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.o_w_2dA86_ZOKZTfuiaeb5FKIb_GxUsY0IcpZJd5wUcNTTP5b01w4NxNqPUF6SRunbpPWM3sQPwyOyBQ1hqabBW1OKxFnWenmPMJEuy3DVT1ohS4Y833OdiJnHTmiIP97J_VfzYDejBYY09oyih-KDUZcUyfBaIF2tZUSl2I79HsPa2wwVwuW-HX0A4D3lUki_c-QYtaPp5_n-xUh1mrQSJDVVHigh0f5od6eWPZ2enXRNZOONV1HZEQpdDHcF5cdT4CPsapfY4gOKsEGZH1F-kLhQDgGKiHprRDAna0E4LC6orMsUFMuEJIYqweyXvYbO_apSG-X7IiomOt-mYA1w


###admin
GET https://127.0.0.1:56901/api/v1/namespaces/default/pods
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6IjAxUnNSSzRhNjJWOXZYdGVZYk81TkhLLXYtUVlKVzg1QUJCVkVnRW9hRjgifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImNsdXN0ZXItcm9sZS1hZG1pbi1zZWNyZXQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiY29tbXZhdWx0LWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiNWFjYTAyOTctOGQ5YS00NzM1LTg4MmMtZDk1YjlmNzJlMjAxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6Y29tbXZhdWx0LWFkbWluIn0.JLBoWVWxn0kGq2QZduunAixAQd5L0u4VMyiXxKc08EUxH4PnH2_wdmP8flSEQJcHz49pqTEHYTD8ed6px1XfSYLh4mvTUIFv905WCZ923-wSMcc8HhIHDoFszMgYu28ZKs55TyMoowoR4GrrDe0z69mN9IpGkZFi6yphgoaMyothi2Rf8denbZaST8pdVOFc8E_oa-ne0Qfn0J2qFnTUZGtS-OnI7TvoewHO9zcRoIXHTF_KKRRJWCNklH4uyCWzPDSDv834-FCpE52PMfDDhNVPgdIUHLddF1rRdAChFDoYDopXtQyHZWw-Bw_44v_LqVpjP8OovoAtqZad9xaLxQ