apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-demo
  name: nginx-demo
spec:
  containers:
  - image: nginx:latest
    name: nginx-demo
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
